"""
GitHub PR Review Script — uses Anthropic API directly.

Fetches PR diff, sends to Claude for review, posts comments back to PR.
"""
import os
import requests

ANTHROPIC_API_KEY = os.environ["ANTHROPIC_API_KEY"]
PR_NUMBER = os.environ["PR_NUMBER"]
GITHUB_TOKEN = os.environ["GITHUB_TOKEN"]
REPO = os.environ["REPO"]  # format: "owner/repo"
OWNER, REPO_NAME = REPO.split("/")

HEADERS = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github.v3+json",
}


def get_pr_details():
    """Fetch PR title, body, and changed files."""
    url = f"https://api.github.com/repos/{OWNER}/{REPO_NAME}/pulls/{PR_NUMBER}"
    resp = requests.get(url, headers=HEADERS)
    resp.raise_for_status()
    pr = resp.json()
    return {
        "title": pr["title"],
        "body": pr["body"] or "",
        "head": pr["head"]["ref"],
        "base": pr["base"]["ref"],
    }


def get_pr_files():
    """Get list of changed files in PR."""
    url = f"https://api.github.com/repos/{OWNER}/{REPO_NAME}/pulls/{PR_NUMBER}/files"
    resp = requests.get(url, headers=HEADERS)
    resp.raise_for_status()
    return resp.json()


def get_file_diff(filename):
    """Get the diff content for a file."""
    files = get_pr_files()
    for f in files:
        if f["filename"] == filename:
            return f.get("patch", f.get("diff", ""))
    return ""


def get_agent_prompt():
    """Read the agent prompt template."""
    try:
        with open(".claude/agents/pr-review-agent.md", "r") as f:
            return f.read()
    except FileNotFoundError:
        return ""


def review_with_claude(pr_details, files, agent_prompt):
    """Send PR info to Claude API for review."""
    import anthropic

    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    # Build a summary of changed files
    file_summary = []
    for f in files:
        file_summary.append(f"- {f['filename']}: +{f['additions']} -{f['deletions']}")

    changed_files_text = "\n".join(file_summary)

    message = f"""You are reviewing PR #{PR_NUMBER} to {pr_details['base']}.

PR Title: {pr_details['title']}
PR Body: {pr_details['body']}

Changed Files:
{changed_files_text}

{agent_prompt}

Based on the changed files and your review criteria, provide your code review comments.
Focus on correctness, edge cases, security, patterns, and test coverage.
Be constructive and specific. Cite file names and line numbers where relevant.
"""

    response = client.messages.create(
        model="claude-opus-4-7",
        max_tokens=4096,
        messages=[{"role": "user", "content": message}],
    )

    return response.content[0].text


def post_pr_comment(comment_body):
    """Post a comment to the PR."""
    url = f"https://api.github.com/repos/{OWNER}/{REPO_NAME}/issues/{PR_NUMBER}/comments"
    payload = {"body": comment_body}
    resp = requests.post(url, headers=HEADERS, json=payload)
    resp.raise_for_status()
    return resp.json()


def main():
    print(f"Reviewing PR #{PR_NUMBER}...")

    # Fetch PR details
    pr_details = get_pr_details()
    print(f"PR: {pr_details['title']}")

    # Fetch changed files
    files = get_pr_files()
    print(f"Changed files: {len(files)}")

    # Get agent prompt
    agent_prompt = get_agent_prompt()

    # Get review from Claude
    review_text = review_with_claude(pr_details, files, agent_prompt)
    print(f"Review length: {len(review_text)} chars")

    # Post comment to PR
    comment = f"## Code Review\n\n{review_text}\n\n---\n*Review generated by Claude Code*"
    post_pr_comment(comment)
    print("Review posted to PR!")


if __name__ == "__main__":
    main()
